### ISSUE TITLE
Tests fails with "ArgumentException : File not found" instead of comparison

### ISSUE THREAD

**Issue by tom-englert** [VerifyTests/Verify.ImageSharp#404]
#### Describe the bug

When the image changes, the test fails - which of course is expected. 

However the tests fail with `System.ArgumentException : File not found. Path: [...]\Samples.VerifyImage.01.received.png` instead of comparing received vs. verified image.

#### Minimal Repro

Change the color value in line 31:
https://github.com/VerifyTests/Verify.ImageSharp/blob/9ba789d4705fd704e6dcca32c8572e6e2c4daac0/src/Tests/Samples.cs#L26-L34

=> Test fails like described above.

#### Submit a PR that fixes the bug

I've looked through the code, but did not find something wrong - maybe the issue is located in the Verify core engine?

**Comment by SimonCropp** [comment]
what versions of `Verify.ImageSharp` and  `Verify` r u using?

**Comment by tom-englert** [comment]
Just tried with the latest sources from main branch, still happening, so it's 
https://github.com/VerifyTests/Verify.ImageSharp/blob/9ba789d4705fd704e6dcca32c8572e6e2c4daac0/src/Verify.ImageSharp/Verify.ImageSharp.csproj#L7

**Comment by SimonCropp** [comment]
i can repro. can u share a fialing repro sln?

**Comment by tom-englert** [comment]
https://github.com/tom-englert/Verify.ImageSharp/tree/issue%23404

P.S. When I delete `Samples.VerifyImage.01.verified.png`, then `Samples.VerifyImage.01.received.png` will be created.

**Comment by tom-englert** [comment]
Seems to be related to running in VisualStudio:
https://ci.appveyor.com/project/SimonCropp/verify-imagesharp/builds/42729393

**Comment by tom-englert** [comment]
Running `dotnet test` locally also fails as expected. (SDK Version: 6.0.200)

**Comment by tom-englert** [comment]
When I remove `.UseExtension("png")`, it only compares the image meta data (`*.txt`), and it does not fail when the content of the bitmap changes.

**Comment by tom-englert** [comment]
When I omit `.UseExtension("png")`, `IsImage(...)` is called with `extension` == `null`, so it never detects testee as an image:

https://github.com/VerifyTests/Verify.ImageSharp/blob/9ba789d4705fd704e6dcca32c8572e6e2c4daac0/src/Verify.ImageSharp/VerifyImageSharp.cs#L12-L28

When I remove the `&& requiredExtension == extension` from the code above, it starts comparing the images, but the file name is `*.received.bmp`

**Comment by tom-englert** [comment]
Tried this and moved `.png` to the top, so it gets the default:
https://github.com/tom-englert/Verify.ImageSharp/blob/31d7995623e6faebc8bc823351c63679c2906bee/src/Verify.ImageSharp/VerifyImageSharp.cs#L12-L27

=> Now I get the `File not found` again, even without `.UseExtension("png")`

**Comment by SimonCropp** [comment]
ok. i will look at this again

**Comment by tom-englert** [comment]
I think it's here:
https://github.com/VerifyTests/Verify/blob/7942855bd13dca30ce8c2efc3a3fa66285790bad/src/Verify/Compare/FileComparer.cs#L23-L27
If it steps into this, the "received" file is not generated.

**Comment by SimonCropp** [comment]
can u try 3.8.0

**Comment by tom-englert** [comment]
I have added a bunch of tests to resemble this scenario in https://github.com/VerifyTests/Verify/pull/492, and fixed another issue there.
Can you merge/publish this?

**Comment by tom-englert** [comment]
Superseded by other fix.
